CREATE TABLE Clientes (
    Id BIGINT PRIMARY KEY IDENTITY(1,1),
    Nombre NVARCHAR(MAX) NOT NULL,
    Telefono NVARCHAR(MAX),
    Email NVARCHAR(MAX),
    Direccion NVARCHAR(MAX)
);


CREATE TABLE Vehiculos (
    Id BIGINT PRIMARY KEY IDENTITY(1,1),
    ClienteId BIGINT FOREIGN KEY REFERENCES Clientes(Id),
    Marca NVARCHAR(MAX) NOT NULL,
    Modelo NVARCHAR(MAX) NOT NULL,
    Año INT,
    Placa NVARCHAR(MAX) UNIQUE NOT NULL
);


CREATE TABLE Servicios (
    Id BIGINT PRIMARY KEY IDENTITY(1,1),
    Nombre NVARCHAR(MAX) NOT NULL,
    Descripcion NVARCHAR(MAX),
    Precio DECIMAL(10, 2) NOT NULL
);


CREATE TABLE OrdenesServicio (
    Id BIGINT PRIMARY KEY IDENTITY(1,1),
    ClienteId BIGINT FOREIGN KEY REFERENCES Clientes(Id),
    VehiculoId BIGINT FOREIGN KEY REFERENCES Vehiculos(Id),
    ServicioId BIGINT FOREIGN KEY REFERENCES Servicios(Id),
    Fecha DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    Estado NVARCHAR(MAX) NOT NULL,
    Total DECIMAL(10, 2) NOT NULL
);